[tool.ruff]
line-length = 1000
target-version = "py310"
lint.select = ["E", "F", "I", "UP"]
lint.ignore = ["D203"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_functions = "test_*"
